---
- name: Got configure files in main path.
  ansible.builtin.find:
    path: "/etc/nginx"
    file_type: any
    recurse: true
  register: nginx_dir_content
  when: nginx_custom_app_enabled

- name: Recursively change ownership.
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: "{{ customize_owner_user }}"
    group: "{{ customize_owner_group }}"
  with_items: "{{ nginx_dir_content.files }}"
  become: true
  become_user: root
  when: nginx_dir_content is defined

- name: Ensure custom base path provided.
  ansible.builtin.file:
    path: "{{ customize_base_path }}"
    state: directory
    mode: '0755'
    owner: "{{ customize_owner_user }}"
    group: "{{ customize_owner_group }}"
  when: customize_base_path is defined

- name: Ensure custom log path provided
  ansible.builtin.file:
    path: "{{ customize_base_cache_path }}"
    state: directory
    mode: '0755'
    owner: "{{ customize_owner_user }}"
    group: "{{ customize_owner_group }}"
  when: customize_base_cache_path is defined

- name: Ensure custom log path provided
  ansible.builtin.file:
    path: "{{ customize_base_log_path }}"
    state: directory
    mode: '0755'
    owner: "{{ customize_owner_user }}"
    group: "{{ customize_owner_group }}"
  when: customize_base_log_path is defined

- name: Ensure custom ssl path provided
  ansible.builtin.file:
    path: "{{ customize_base_ssl_path }}"
    state: directory
    mode: '0755'
    owner: "{{ customize_owner_user }}"
    group: "{{ customize_owner_group }}"
  when: customize_base_ssl_path is defined

- name: Ensure custom pid path provided
  ansible.builtin.file:
    path: "{{ customize_base_pid_path }}"
    state: directory
    mode: '0755'
    owner: "{{ customize_owner_user }}"
    group: "{{ customize_owner_group }}"
  when: customize_base_pid_path is defined

- name: Got pid file stat.
  ansible.builtin.stat:
    path: "{{ customize_base_pid_path }}/{{ customize_file_pid_name }}"
  register: pid_file
  when:
    - customize_base_pid_path is defined
    - customize_file_pid_name is defined

- name: Ensure custom pid file provided.
  ansible.builtin.file:
    path: "{{ customize_base_pid_path }}/{{ customize_file_pid_name }}"
    mode: '0644'
    state: 'touch'
    owner: "{{ customize_owner_user }}"
    group: "{{ customize_owner_group }}"
  when:
    - pid_file.stat.exists is defined
    - not pid_file.stat.exists

- name: Apply custom main configure
  ansible.builtin.template:
    src: conf/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: "0644"
  become: true
  become_user: root
  notify: (Handler) Run NGINX
  when: nginx_custom_app_enabled
