---
- name: (Alpine Linux) Install logrotate
  community.general.apk:
    name: "{{ nginx_logrotate_package }}"
  when: ansible_facts['os_family'] == 'Alpine'
  become: true
  become_user: root

- name: (Debian/Ubuntu) Install logrotate
  ansible.builtin.apt:
    name: "{{ nginx_logrotate_package }}"
    state: present
  when: ansible_facts['os_family'] == 'Debian'
  become: true
  become_user: root

- name: (Amazon Linux/CentOS/Oracle Linux/RHEL) Install logrotate
  ansible.builtin.yum:
    name: "{{ nginx_logrotate_package }}"
    state: present
  when: ansible_facts['os_family'] == 'RedHat'
  become: true
  become_user: root

- name: (SLES) Install Logrotate
  community.general.zypper:
    name: "{{ nginx_logrotate_package }}"
    state: present
  when: ansible_facts['os_family'] == 'Suse'
  become: true
  become_user: root

- name: Create logrotate config
  ansible.builtin.template:
    src: logrotate/nginx.j2
    dest: /etc/logrotate.d/nginx
    mode: "0644"
  become: true
  become_user: root
  notify: (Handler) Run logrotate
