---
role_name_check: 1
driver:
  name: docker
platforms:
  - name: rhel-8
    image: redhat/ubi8:8.9
    # # platform: s390x
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /usr/sbin/init
  - name: rhel-9
    image: redhat/ubi9:9.1.0
    # platform: aarch64
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /usr/sbin/init
provisioner:
  name: ansible
  log: true
  playbooks:
    converge: converge.yml
    verify: verify.yml
  
