---
- name: Converge
  hosts: all
  gather_facts: true
  vars:
    # nginx_modules:
    #   - geoip
    #   - image-filter
    #   - njs
    #   - perl
    #   - xslt
    nginx_offline_installed: true
    nginx_custom_app_enabled: true
    nginx_install_from: 'offline_pkg'
    nginx_offline_dependencies_basepath: "{{ playbook_dir }}/../../offline/pkg/"
    nginx_offline_main_basepath: "{{ playbook_dir }}/../../offline/nginx/"
    nginx_service_modify: true
    nginx_service_timeout: 95
    nginx_logrotate_conf_enable: true
    nginx_logrotate_conf:
      paths:
        - /app/nginx/log/*.log
      options:
        - daily
        - missingok
        - rotate 14
        - compress
        - delaycompress
        - notifempty
        - sharedscripts
        - create 0644 capco-user capco-user
  tasks:
    - name: Debug starting state
      debug:
        msg: "Starting molecule test...."
    - name: Install NGINX
      include_role:
        name: ansible-role-nginx
