---
role_name_check: 1
driver:
  name: default
platforms:
  - name: instance
    group:
      - az_test
    managed: false
lint: |
  set -e
  yamllint .
  ansible-lint .

provisioner:
  name: ansible
  inventory:
    host_vars:
      instance:
        ansible_host: 4.194.50.52
        ansible_port: 22
        ansible_user: 'capco-user'
        ansible_ssh_private_key_file: /Users/wywt/Documents/Projects/BBL/ssh-key/api.pem
  playbooks:
    converge: converge.yml
    verify: verify.yml
verifier:
  name: ansible
scenario:
  name: azure
  converge_sequence:
    - converge
    - idempotence
    - verify
